sudo: required
services:
    - docker

before_install:
    - docker build -t jagadalac/docker-react -f Dockerfile.dev .

script:
    - docker run jagadalac/docker-react npm run test -- --coverage --watchAll=false

deploy:
    provider: elastickbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-684264318334"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
